### ISSUE TITLE
Fully implement import/export functionality

### ISSUE THREAD

**Issue by rmadamson** [olcf/pkpass#1]

**Comment by ginsburgnm** [comment]
Export/import functionality could be implemented as such:
the password files that a user has are all conglomerated into one large backup yaml file. The metadata would be preserved, and the passwords would be decrypted by the export, and then re-encrypted using something like AES. The user would then type the password in on "import" and resign the passwords with the new badge/cert/whatever.

**Comment by ginsburgnm** [comment]
should be closed by #33
