### ISSUE TITLE
Add specific card reader whitelisting and blacklisting capability

### ISSUE THREAD

**Issue by rmadamson** [olcf/pkpass#11]
See pkcs11-tool with 3 card readers:  One ACS white usb-c and two ubi-key usbc readers:

```
ryan@lappy486:~/git$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico Yubikey 4 CCID 01
  token label        : PIV_II (PIV Card Holder pin)
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 879b355cb9eeff59
Slot 1 (0x4): ACS ACR39U ICC Reader
  token label        : PIV_II (PIV Card Holder pin)
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 4ce48d80a610d7eb
Slot 2 (0x8): Yubico Yubikey 4 CCID
  token label        : PIV_II (PIV Card Holder pin)
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 780a6656470c55be
```

We can detect and prefer serial numbers, manufacturers, or slots

**Comment by ginsburgnm** [comment]
In addition we also have the upright card readers that would look something like this
Available slots:
Slot 0 (0x0): OMNIKEY AG 3121 USB 00 00
    token label                : PIV Card Holder pin (PIV_II)
    token manufacturer  : piv_II
    token model              : PKCS#15 emulated
    token flags                : login required, rng, token initialized, PIN initialized
    hardware version      : 0.0
    firmware version       : 0.0
    serial num                 : dae608a8421843e2
    pin min/max              : 4/8

**Comment by ginsburgnm** [comment]
In addition we have the upright omnikey card readers that would have output similar to the following
`n0g@nginsburg-desktop:~/git/pkpass$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): OMNIKEY AG 3121 USB 00 00
    token label                : PIV Card Holder pin (PIV_II)
    token manufacturer  : piv_II
    token model             : PKCS#15 emulated
    token flags               : login required, rng, token initialized, PIN initialized
    hardware version     : 0.0
    firmware version      : 0.0
    serial num                : dae608a8421843e2
    pin min/max             : 4/8

`

**Comment by ginsburgnm** [comment]
We may want to look at this library
https://pkcs11wrap.sourceforge.io/api/samples.html#dump-all-the-token-objects
It appears that this library may already be able to parse and list multiple readers. Though I only took a cursory glance at it

**Comment by ginsburgnm** [comment]
This functionality was solved via the card slots option.
