### ISSUE TITLE
Error when no private key directory found

### ISSUE THREAD

**Issue by rmadamson** [olcf/pkpass#16]
Pkpass fails with:
 ```
(pkpass) ryan@ryansapro:~/git/pkpass$ ./pkpass.py create
Enter Pin/Passphrase: 

FileOpenError: File ./private found in config, could not be opened due to No such file or directory
```

When 'private' is not in the pkpassrc file.  'private' does not need to be defined for a successful run (i.e. when using a smartcard) so this should be a warning.

**Comment by rmadamson** [comment]
This also happens when the directory exists, but no valid certificates with the extension '.cert' are found.

I think expected behavior would be to bail or warn if no certificates or identities end up being loaded, with some sort of appropriate error message.

**Comment by ginsburgnm** [comment]
we could modify def load_keys_from_directory in libpkpass/identities.py to something like
`
if os.path.isdir(path):
    self._load_from_directory(path, 'key')
else:
    print "WARNING: PRIVATE KEY DIRECTORY DOES NOT EXISTS"
`
This would allow the user to bypass the private keys from being loaded in, but still inform the user that the configuration is missing the private key directory
