### ISSUE TITLE
Show 'verbose' errors only if verbose is true

### ISSUE THREAD

**Issue by rmadamson** [olcf/pkpass#17]
As an example:  If the ca.bundle does not exist or is not valid, we can end up seeing a stack trace, due to the way that we print error messages that we gather.  It's pretty easy to see that we're getting that trustchainverificationerror, but maybe we don't want to see the full output/stack trace of the exception that we caught unless we're running in verbose mode.  In this case, just the first line may be sufficient and we can mask the openssl output when something goes funky.

```
TrustChainVerificationError: Error loading file /Users/uua/passdb/cabundles/ca.bundle
95931:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/bio/bss_file.c:126:fopen('/Users/uua/passdb/cabundles/ca.bundle','r')
95931:error:2006D080:BIO routines:BIO_new_file:no such file:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/bio/bss_file.c:129:
95931:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/x509/by_file.c:274:
usage: verify [-verbose] [-CApath path] [-CAfile file] [-purpose purpose] [-crl_check] [-engine e] cert1 cert2 ...
recognized usages:
	sslclient 	SSL client
	sslserver 	SSL server
	nssslserver	Netscape SSL server
	smimesign 	S/MIME signing
	smimeencrypt	S/MIME encryption
	crlsign   	CRL signing
	any       	Any Purpose
	ocsphelper	OCSP helper
```

**Comment by ginsburgnm** [comment]
I remember discussing this in person. I don't remember were we fell on this specific case; this I believe was the macos specific issue; as this traceback does not happen on my ubuntu desktop, but I did observe it on my Macbook.

**Comment by ginsburgnm** [comment]
This specific instance does not happen, with the resolution of defect #18 Are there other scenarios in which we see this issue @rmadamson ?

**Comment by ginsburgnm** [comment]
added verbosity flag for some commands; closing for now
