### ISSUE TITLE
openssl changes

### ISSUE THREAD

**Issue by ginsburgnm** [olcf/pkpass#199]
rsautl has been deprecated and is causes issues within unit tests on github actions, it's currently still working as expected on my local linux instance. 

Additionally the fingerprint hash default has changed from sha1 to sha256, this screws up indexing since we initially didn't specify a type.

**Comment by carljbai** [comment]
#201 should address the rsautl deprecation. It looks like 51ef1f5 already addressed the fingerprint hash default change.
