### ISSUE TITLE
Better Exception Handling

### ISSUE THREAD

**Issue by rmadamson** [olcf/pkpass#6]
Catch exceptions related to directories not existing for cert/key/passdb directories

**Comment by rmadamson** [comment]
Errors related to passwords that do not exist should be handled nicely.

**Comment by rmadamson** [comment]
command.py line 92, test for blank user and then throw an error if not specified

**Comment by rmadamson** [comment]
command.py line 92, test for blank user and then throw an error if not specified

**Comment by ginsburgnm** [comment]
Specific instances that have been pointed out have been handled. As the issue has such a generic name; I'm going to count this as closed, if there comes to be a specific bug later, we can open a new ticket.
