### ISSUE TITLE
Create escrow capability

### ISSUE THREAD

**Issue by rmadamson** [olcf/pkpass#8]
Let users set a list of 'escrow' users that get passwords automatically encrypted for them if the credentials exist.  Maybe this should by default be an 'escrow' user name.

Sites can put pre-commit hooks into their password-related git repositories to see if all yaml files include encrypted passwords for the escrow users.  It's up to the sites to only merge passwords that have also been sent to escrow accounts

**Comment by ginsburgnm** [comment]
closed by #29 and #30
